### ISSUE TITLE
Extra matrixes

### ISSUE THREAD

**Issue by SemionMcAlice** [dynaTrace/Dynatrace-SOLR-Monitoring-FastPack#1]
Hey,
i'm wondering how difficult is it to add SOLR's cache usages to this module?

semion

**Comment by ingohackl** [comment]
Hi Semion,

sorry I can't give you an answer for this since the original developer of this fastpack has left Dynatrace.

Ingo

**Comment by SemionMcAlice** [comment]
Hey Ingo,
thank you for getting back to me.
to bad though.
Semion

**Comment by Dynatrace-Dave-Mauney** [comment]
Hi Semion,

You might want to check https://github.com/dynaTrace/Dynatrace-SOLR-Remote-Monitoring-Plugin for cache usage details.

See details here: https://community.dynatrace.com/community/display/DL/SOLR+Remote+Monitoring+Plugin

Thanks,

dave

**Comment by SemionMcAlice** [comment]
Hey Dave,
thank you for that. we'll have a look at it.
from a quick look at it it looks like it is what we need.

thank you,
Semion
